In [18]:
# TODO: Delete this file before merging to development

import pandas as pd
import importlib

from sklearn.metrics import roc_auc_score
import realkd.rules
importlib.reload(realkd.rules)

titanic = pd.read_csv('../datasets/titanic/train.csv')
titanic.dropna(inplace=True)
survived = titanic.Survived
titanic.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin', 'Survived'], inplace=True)
titanic.drop(columns=['Sex', 'Embarked'],  inplace=True)
re = realkd.rules.RuleBoostingEstimator(base_learner=realkd.rules.XGBRuleEstimator(loss=realkd.rules.logistic_loss))
re.fit(titanic, survived.replace(0, -1)).rules_
titanic

['Pclass' 'Age' 'SibSp' 'Parch' 'Fare']
[[  1.      38.       1.       0.      71.2833]
 [  1.      35.       1.       0.      53.1   ]
 [  1.      54.       0.       0.      51.8625]
 [  3.       4.       1.       1.      16.7   ]
 [  1.      58.       0.       0.      26.55  ]
 [  2.      34.       0.       0.      13.    ]
 [  1.      28.       0.       0.      35.5   ]
 [  1.      19.       3.       2.     263.    ]
 [  1.      49.       1.       0.      76.7292]
 [  1.      65.       0.       1.      61.9792]
 [  1.      45.       1.       0.      83.475 ]
 [  2.      29.       0.       0.      10.5   ]
 [  3.      25.       0.       0.       7.65  ]
 [  1.      23.       3.       2.     263.    ]
 [  1.      46.       1.       0.      61.175 ]
 [  1.      71.       0.       0.      34.6542]
 [  1.      23.       0.       1.      63.3583]
 [  1.      21.       0.       1.      77.2875]
 [  1.      47.       0.       0.      52.    ]
 [  1.      24.       0.       1.     247.5208]


AttributeError: 'numpy.ndarray' object has no attribute 'iloc'